# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: pi_custom_metrics

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - package_name: datadog_custom_metrics
    maintainer: Antonin Bruneau <antonin.bruneau@gmail.com>
    license: "MIT"
    formats:
      - deb
    contents:
      - src: config/config.yaml
        dst: /etc/datadog-custom-metrics/config.yaml
        type: config
      - src: scripts/datadog-custom-metrics.service
        dst: /etc/systemd/system/datadog-custom-metrics.service
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
